import type { RetroQuestion } from './domain';

/**
 * The retrospective prompts, in the order that decides which one falls on
 * which day. Ids are the contract: every stored answer keeps the id of the
 * question it answered, so an id must never be reused for a different
 * question. Rewording a prompt is safe -- the id stays, and old answers
 * follow the new text. Adding or removing one reshuffles which prompt lands
 * on which future date, which is harmless; past answers keep their own.
 */
export const RETRO_QUESTIONS: RetroQuestion[] = [
  { id: 'energie', text: 'Co dneska stálo nejvíc energie — a stálo to za to?' },
  { id: 'nechtelo', text: 'Udělal jsi dnes něco, co se ti nechtělo?' },
  { id: 'odlozil', text: 'Co jsi odložil a proč zrovna to?' },
  { id: 'pochvala', text: 'Za co bys sám sebe dneska pochválil?' },
  { id: 'hrdy', text: 'Za co na sebe můžeš být dnes hrdý?' },
  { id: 'jinak', text: 'Co bys udělal jinak, pokud bys zažil dnešek znovu?' },
  { id: 'slo-samo', text: 'Kdy ti to dneska šlo samo?' },
  { id: 'rozhodilo', text: 'Co tě rozhodilo a jak dlouho trvalo se vrátit?' },
  { id: 'o-sobe', text: 'Co ses dneska dozvěděl o sobě?' },
  { id: 'noveho', text: 'Co ses dneska dozvěděl nového?' },
  { id: 'unava-hlava', text: 'Bránila ti víc únava, nebo hlava?' },
  { id: 'zmenit-jednu', text: 'Pokud bys mohl na dnešku změnit jednu věc, co by to bylo?' },
  { id: 'zitrek', text: 'Kdyby měl být zítřek lepší o jednu jedinou věc, jaká?' },
  { id: 'rekl-ne', text: 'Na co jsi dneska řekl ne?' },
  { id: 'za-tyden', text: 'Co z dneška bude mít smysl ještě za týden?' },
  { id: 'vdecny', text: 'Za co jsi vděčný?' },
  { id: 'obetoval', text: 'Co jsi dnes obětoval pro svůj vysněný život?' },
  { id: 'posledni-den', text: 'Pokud by dnes byl tvůj poslední den, stál by za to?' },
  { id: 'emoce', text: 'Kdy jsi dneska nezvládl svoje emoce?' },
  { id: 'smysluplnost', text: 'Co mi dnes dalo pocit smysluplnosti?' },
  { id: 'automaticky', text: 'Jaké rozhodnutí jsem dnes udělal automaticky, aniž bych ho vědomě zvážil?' },
  { id: 'za-rok', text: 'Co by si o mém dnešním dni myslel člověk, kterým chci za rok být?' },
  { id: 'potvrzeni-zvenci', text: 'Kde jsem dnes hledal potvrzení nebo pochvalu zvenčí místo toho, abych se spolehl na vlastní úsudek?' },
  { id: 'smerovani', text: 'Kdyby dnešek byl jediný ukazatel mého směřování, kam bych podle něj mířil?' },
  { id: 'klid', text: 'Kdy jsi dneska naposled cítil klid?' },
  { id: 'radost-komu', text: 'Komu jsi dneska udělal radost?' },
  { id: 'rozptyleni', text: 'Co tě dneska nejvíc rozptýlilo?' },
  { id: 'bal-se', text: 'Čeho ses dneska bál a co by se stalo, kdybys do toho šel?' },
  { id: 'pokazil', text: 'Co jsi dneska pokazil a co s tím uděláš?' },
  { id: 'peti-letech', text: 'Dělal jsi dneska něco, co bude mít smysl za pět let?' },
  { id: 'trpelivost', text: 'Kdy ti dneska došla trpělivost?' },
  { id: 'ztracena-hodina', text: 'Kdy jsi dneska ztratil hodinu a nevšiml sis toho?' },
  { id: 'sebeovladani', text: 'Co tě dneska stálo nejvíc sebeovládání?' },
  { id: 'pomohl-kdo', text: 'Kdo ti dneska pomohl, aniž bys o to požádal?' },
  { id: 'telefon-bez-duvodu', text: 'Kdy jsi dneska sáhl po telefonu bez důvodu?' },
  { id: 'proti-pohodli', text: 'Kdy jsi dneska šel proti pohodlí?' },
  { id: 'naucil-prace', text: 'Co ses dneska naučil o své práci?' },
  { id: 'zalezi-dlouhodobe', text: 'Co dneska posunulo něco, na čem ti dlouhodobě záleží?' },
  { id: 'stydel', text: 'Za co ses dneska styděl?' },
  { id: 'utraceny-cas', text: 'Za co jsi dneska utratil čas, který se nedá vrátit?' },
  { id: 'spanek', text: 'Jak jsi dneska spal a jak se to projevilo?' },
  { id: 'neozval', text: 'Na koho sis dneska vzpomněl a neozval ses mu?' },
  { id: 'bez-telefonu', text: 'Co bys dneska stihl navíc bez telefonu?' },
  { id: 'odvaha-skryta', text: 'Co dneska vyžadovalo odvahu, i když to zvenku nevypadalo?' },
  { id: 'nikdo-nekontroloval', text: 'Co jsi dneska udělal, i když to nikdo nekontroloval?' },
  { id: 'o-tobe', text: 'Kolik z dnešního dne bylo o tobě a kolik o očekáváních ostatních?' },
  { id: 'zavist', text: 'Kdy jsi dneska cítil závist?' },
  { id: 'drobnost', text: 'Jakou drobnost sis dneska užil?' },
  { id: 'telo-rika', text: 'Co ti dneska tělo zkoušelo říct?' },
  { id: 'podekovat', text: 'Komu jsi dneska měl poděkovat?' },
  { id: 'mysl-dokola', text: 'Jakou myšlenku sis dneska přehrával dokola?' },
  { id: 'prinutil-rad', text: 'Kdy ses dneska přinutil a byl jsi za to rád?' },
  { id: 'nesel-plan', text: 'Co dneska nešlo podle plánu a jak jsi zareagoval?' },
  { id: 'pravidlo-pomohlo', text: 'Jaké pravidlo ti dneska pomohlo?' },
  { id: 'lhal-sobe', text: 'Kdy jsi dneska lhal, i když jen sobě?' },
  { id: 'zasmal', text: 'Kdy ses dneska naposled zasmál?' },
  { id: 'jidlo-stres', text: 'Co jsi dneska snědl, protože jsi to chtěl, a co ze stresu?' },
  { id: 'odpusteni', text: 'Za co bys dneska měl někoho poprosit o odpuštění?' },
  { id: 'nesel-z-hlavy', text: 'Co ti dneska nešlo z hlavy?' },
  { id: 'prinutil-zbytecne', text: 'Kdy ses dneska přinutil zbytečně?' },
  { id: 'cas-nadarmo', text: 'Co ti dneska vzalo nejvíc času a nestálo to za to?' },
  { id: 'pravidlo-porusil', text: 'Jaké pravidlo jsi dneska porušil?' },
  { id: 'hral-jineho', text: 'Kdy jsi dneska hrál někoho jiného?' },
  { id: 'inspiroval', text: 'Kdo tě dneska inspiroval?' },
  { id: 'zvyk', text: 'Co jsi dneska dělal jen ze zvyku?' },
  { id: 'nejtezsi', text: 'Jakou nejtěžší věc jsi dneska zvládl?' },
  { id: 'za-mesic-jedno', text: 'Co z toho, co tě dneska trápilo, bude za měsíc jedno?' },
  { id: 'neco-dal', text: 'Co jsi dneska dal, aniž bys čekal něco zpátky?' },
  { id: 'rekl-mrzi', text: 'Co jsi dneska řekl a mrzí tě to?' },
  { id: 'zvladas', text: 'Kdy jsi dneska měl pocit, že to zvládáš?' },
  { id: 'setrvacnost', text: 'Kolik z dneška bylo tvoje rozhodnutí a kolik setrvačnost?' },
  { id: 'penize-stalo', text: 'Co dneska stálo peníze a stálo to za to?' },
  { id: 'sam-sebou', text: 'Kdy ses dneska cítil nejvíc sám sebou?' },
  { id: 'pomohl-nechtelo', text: 'Kdy jsi dneska pomohl, i když se ti nechtělo?' },
  { id: 'neco-videl', text: 'Co jsi dneska udělal jen proto, aby to někdo viděl?' },
  { id: 'nezvladas', text: 'Kdy jsi dneska měl pocit, že to nezvládáš?' },
  { id: 'pamatujes', text: 'Kolik z dneška si vůbec pamatuješ?' },
  { id: 'za-mesic-porad', text: 'Co z toho, co tě dneska trápilo, bude za měsíc pořád?' },
  { id: 'neco-nerekl', text: 'Co jsi dneska neřekl, i když jsi měl?' },
  { id: 'hotove', text: 'Co je dneska hotové a včera nebylo?' },
  { id: 'zbytecny-strach', text: 'Čeho ses dneska zbytečně bál?' },
  { id: 'inspirace-jiny', text: 'Co dneska udělal někdo jiný a ty by ses tím mohl inspirovat?' },
  { id: 'nemam-cas', text: 'Kdy jsi dneska řekl „nemám čas“ a nebyla to pravda?' },
  { id: 'fungovalo-zopakuji', text: 'Co dneska fungovalo tak dobře, že to zopakuješ?' },
  { id: 'cizi-nazor', text: 'Čí názor tě dneska ovlivnil víc, než by měl?' },
  { id: 'odmitl-chtelo', text: 'Co jsi dneska odmítl, i když se ti chtělo?' },
  { id: 'nechal-dobre', text: 'Co jsi dneska nechal být a udělal jsi dobře?' },
  { id: 'zapamatovat', text: 'Co si z dneška chceš zapamatovat?' },
  { id: 'zustalo-v-tobe', text: 'Co ti dneska někdo řekl a zůstalo to v tobě?' },
  { id: 'nechal-spatne', text: 'Co jsi dneska nechal být a neměl jsi?' },
  { id: 'zapomenout', text: 'Co bys z dneška nejradši zapomněl?' },
  { id: 'stalo-za-unavu', text: 'Co dneska stálo za tu únavu?' },
  { id: 'bez-pripominani', text: 'Co jsi dneska udělal, aniž by ti to někdo musel připomínat?' },
  { id: 'vcera-usnadnilo', text: 'Co by ti dneska usnadnilo život, kdybys to udělal včera?' },
  { id: 'podruhe-nefungovalo', text: 'Co dneska nefungovalo už podruhé a přesto jsi to zkusil?' },
  { id: 'zitrek-ukol', text: 'Jaký jeden úkol rozhodne, jestli bude zítřek dobrý?' },
  { id: 'dnesek-k-necemu', text: 'Co uděláš zítra, aby byl dnešek k něčemu?' },
  { id: 'rano-poradil', text: 'Co bys dneska poradil sám sobě z rána?' },
  { id: 'pred-peti-lety', text: 'Kdyby tě dneska viděl člověk, kterým jsi byl před pěti lety, co by řekl?' },
  { id: 'jedno-slovo', text: 'Kdyby měl dnešek jedno slovo, jaké by to bylo?' },
];
